import React from "react";
import { useSearchParams } from "react-router-dom";
import { Download, FileText, Plus, Search, X } from "lucide-react";
import Layout from "../components/Layout";
import CampoMoeda from "../components/CampoMoeda";
import { usePermissaoModulo } from "../lib/permissoes";
import { formatBRL } from "../lib/moeda";
import { mensagemAmigavel } from "../lib/erros";
import { anexarArquivos, carregarApoioLicitacoes, criarTipoLicitacao, listarLicitacoes, salvarLicitacao, situacaoContrato, SITUACOES_CONTRATO } from "../lib/licitacoesContratos";

const VAZIO = { fornecedor_id: "", tipo_id: "", numero: "", objeto: "", data_inicio: "", data_validade: "", valor: 0, secretaria_id: "", observacoes: "", encerrado: false };
const campo = "w-full rounded-lg border border-black/10 bg-white px-3 py-2.5 text-sm text-[#0F2A44] outline-none focus:border-[#C9A227] focus:ring-2 focus:ring-[#C9A227]/15";
const dataBR = (iso) => iso ? iso.slice(0,10).split("-").reverse().join("/") : "—";
const nomeFornecedor = (f) => f?.razao_social || f?.nome_fantasia || "Fornecedor";

function Badge({ item }) { const s = SITUACOES_CONTRATO[situacaoContrato(item)]; return <span className="rounded-full px-2.5 py-1 text-xs font-medium whitespace-nowrap" style={{color:s.cor,background:s.fundo}}>{s.label}</span>; }

export default function LicitacoesContratos() {
  const [parametros] = useSearchParams();
  const { usuario, permissao } = usePermissaoModulo("fornecedores");
  const [itens,setItens]=React.useState([]), [apoio,setApoio]=React.useState({fornecedores:[],tipos:[],secretarias:[]});
  const [carregando,setCarregando]=React.useState(true), [erro,setErro]=React.useState(""), [modal,setModal]=React.useState(false), [salvando,setSalvando]=React.useState(false);
  const [form,setForm]=React.useState(VAZIO), [arquivos,setArquivos]=React.useState([]), [busca,setBusca]=React.useState(""), [tipo,setTipo]=React.useState(""), [secretaria,setSecretaria]=React.useState(""), [situacao,setSituacao]=React.useState(()=>parametros.get("situacao")||"");
  const carregar=React.useCallback(async()=>{setCarregando(true);try{const [lista,base]=await Promise.all([listarLicitacoes(),carregarApoioLicitacoes()]);setItens(lista);setApoio(base);setErro("");}catch(e){setErro(mensagemAmigavel(e,"Não foi possível carregar licitações e contratos."));}finally{setCarregando(false);}},[]);
  React.useEffect(()=>{carregar();},[carregar]);
  const filtrados=React.useMemo(()=>itens.filter(i=>{const texto=`${nomeFornecedor(i.fornecedores)} ${i.numero} ${i.objeto}`.toLowerCase();return(!busca||texto.includes(busca.toLowerCase()))&&(!tipo||i.tipo_id===tipo)&&(!secretaria||i.secretaria_id===secretaria)&&(!situacao||situacaoContrato(i)===situacao);}),[itens,busca,tipo,secretaria,situacao]);
  const contagem=React.useMemo(()=>itens.reduce((a,i)=>{a[situacaoContrato(i)]++;return a;},{vigente:0,vencendo:0,vencido:0,encerrado:0}),[itens]);
  async function salvar(e){e.preventDefault();setSalvando(true);setErro("");try{const registro=await salvarLicitacao(form,null,usuario?.id);await anexarArquivos(registro.id,arquivos);setModal(false);setForm(VAZIO);setArquivos([]);await carregar();}catch(f){setErro(mensagemAmigavel(f,"Não foi possível salvar o registro."));}finally{setSalvando(false);}}
  async function novoTipo(){const nome=window.prompt("Nome do novo tipo:");if(!nome)return;try{const criado=await criarTipoLicitacao(nome);setApoio(a=>({...a,tipos:[...a.tipos,criado].sort((x,y)=>x.nome.localeCompare(y.nome))}));setForm(f=>({...f,tipo_id:criado.id}));}catch(e){setErro(mensagemAmigavel(e,"Não foi possível criar o tipo."));}}
  return <Layout usuario={usuario?{nome:usuario.nome_completo}:undefined}><main className="px-5 py-6 sm:px-8 sm:py-7 text-[#0F2A44]">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#9A7B19]">Fornecedores</p><h1 className="mt-1 text-2xl font-semibold">Licitações e Contratos</h1><p className="mt-1 text-sm text-[#0F2A44]/55">Vigências e documentos vinculados ao cadastro existente do fornecedor.</p></div>{permissao?.pode_cadastrar!==false&&<button onClick={()=>setModal(true)} className="flex items-center gap-2 rounded-lg bg-[#0F2A44] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#173b5d]"><Plus size={16}/>Novo registro</button>}</div>
    <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries(SITUACOES_CONTRATO).map(([id,s])=><button key={id} onClick={()=>setSituacao(situacao===id?"":id)} className={`rounded-xl border bg-white p-4 text-left shadow-sm ${situacao===id?"border-[#C9A227]":"border-black/5"}`}><div className="text-2xl font-semibold" style={{color:s.cor}}>{contagem[id]}</div><div className="mt-1 text-xs text-[#0F2A44]/55">{s.label}</div></button>)}</div>
    <section className="mb-5 grid gap-3 rounded-2xl border border-black/5 bg-white p-4 shadow-sm md:grid-cols-4"><label className="relative md:col-span-1"><Search className="absolute left-3 top-3 text-[#0F2A44]/35" size={16}/><input className={`${campo} pl-9`} placeholder="Fornecedor, número ou objeto" value={busca} onChange={e=>setBusca(e.target.value)}/></label><select className={campo} value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todos os tipos</option>{apoio.tipos.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select><select className={campo} value={secretaria} onChange={e=>setSecretaria(e.target.value)}><option value="">Todas as secretarias</option>{apoio.secretarias.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select><select className={campo} value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="">Todas as situações</option>{Object.entries(SITUACOES_CONTRATO).map(([id,s])=><option key={id} value={id}>{s.label}</option>)}</select></section>
    {erro&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</div>}
    <section className="overflow-hidden rounded-2xl border border-black/5 bg-white shadow-sm">{carregando?<div className="p-10 text-center text-sm text-[#0F2A44]/45">Carregando registros...</div>:filtrados.length===0?<div className="p-12 text-center"><FileText className="mx-auto mb-3 text-[#C9A227]"/><p className="font-medium">Nenhum registro encontrado</p><p className="mt-1 text-sm text-[#0F2A44]/45">Cadastre o primeiro processo ou ajuste os filtros.</p></div>:<div className="divide-y divide-black/5">{filtrados.map(i=><article key={i.id} className="grid gap-4 p-5 hover:bg-[#F8F6EF]/45 lg:grid-cols-[1.2fr_1.6fr_.8fr_auto]"><div><div className="font-semibold">{nomeFornecedor(i.fornecedores)}</div><div className="mt-1 text-xs text-[#0F2A44]/45">{i.tipos_licitacao_contrato?.nome} · {i.numero}</div></div><div><div className="text-sm font-medium">{i.objeto}</div><div className="mt-1 text-xs text-[#0F2A44]/45">{i.secretarias?.nome||"Sem secretaria"}{i.valor?` · ${formatBRL(i.valor)}`:""}</div></div><div><Badge item={i}/><div className="mt-2 text-xs text-[#0F2A44]/50">Validade: {dataBR(i.data_validade)}</div></div><div className="flex min-w-36 flex-col items-end gap-1">{(i.licitacoes_contratos_anexos||[]).map(a=><a key={a.id} href={a.arquivo_url} target="_blank" rel="noreferrer" download className="flex max-w-48 items-center gap-1.5 truncate text-xs text-[#2563EB] hover:underline" title={a.nome}><Download size={13}/>{a.nome}</a>)}</div></article>)}</div>}</section>
    {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#071728]/60 p-4" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form onSubmit={salvar} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-[#F8F6EF] shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-black/5 bg-white px-6 py-4"><div><h2 className="text-lg font-semibold">Novo registro</h2><p className="text-xs text-[#0F2A44]/45">O fornecedor é apenas vinculado; seus dados não são copiados.</p></div><button type="button" onClick={()=>setModal(false)}><X size={20}/></button></header><div className="grid gap-4 p-6 md:grid-cols-2">
      <label className="md:col-span-2 text-xs font-medium">Fornecedor *<select required className={`${campo} mt-1`} value={form.fornecedor_id} onChange={e=>setForm({...form,fornecedor_id:e.target.value})}><option value="">Selecione</option>{apoio.fornecedores.map(f=><option key={f.id} value={f.id}>{nomeFornecedor(f)} · {f.cpf_cnpj||"sem documento"}</option>)}</select></label>
      <label className="text-xs font-medium">Tipo *<div className="mt-1 flex gap-2"><select required className={campo} value={form.tipo_id} onChange={e=>setForm({...form,tipo_id:e.target.value})}><option value="">Selecione</option>{apoio.tipos.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select><button type="button" onClick={novoTipo} className="rounded-lg border border-black/10 px-3" title="Adicionar tipo"><Plus size={16}/></button></div></label>
      <label className="text-xs font-medium">Número *<input required className={`${campo} mt-1`} value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></label>
      <label className="md:col-span-2 text-xs font-medium">Objeto *<textarea required rows="3" className={`${campo} mt-1`} value={form.objeto} onChange={e=>setForm({...form,objeto:e.target.value})}/></label>
      <label className="text-xs font-medium">Assinatura / início *<input required type="date" className={`${campo} mt-1`} value={form.data_inicio} onChange={e=>setForm({...form,data_inicio:e.target.value})}/></label><label className="text-xs font-medium">Validade *<input required type="date" min={form.data_inicio} className={`${campo} mt-1`} value={form.data_validade} onChange={e=>setForm({...form,data_validade:e.target.value})}/></label>
      <label className="text-xs font-medium">Valor do contrato<CampoMoeda className={`${campo} mt-1`} valor={form.valor} onValorChange={v=>setForm({...form,valor:v})}/></label><label className="text-xs font-medium">Secretaria responsável<select className={`${campo} mt-1`} value={form.secretaria_id} onChange={e=>setForm({...form,secretaria_id:e.target.value})}><option value="">Selecione</option>{apoio.secretarias.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label>
      <label className="md:col-span-2 text-xs font-medium">Anexos<input type="file" multiple className={`${campo} mt-1`} onChange={e=>setArquivos([...e.target.files])}/><span className="mt-1 block font-normal text-[#0F2A44]/45">Edital, contrato assinado, aditivos e publicações.</span></label><label className="md:col-span-2 text-xs font-medium">Observações<textarea rows="3" className={`${campo} mt-1`} value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label><label className="md:col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.encerrado} onChange={e=>setForm({...form,encerrado:e.target.checked})}/>Marcar como encerrado</label>
    </div><footer className="flex justify-end gap-2 border-t border-black/5 bg-white px-6 py-4"><button type="button" onClick={()=>setModal(false)} className="rounded-lg border border-black/10 px-4 py-2 text-sm">Cancelar</button><button disabled={salvando} className="rounded-lg bg-[#0F2A44] px-5 py-2 text-sm text-white disabled:opacity-50">{salvando?"Salvando...":"Salvar registro"}</button></footer></form></div>}
  </main></Layout>;
}
