-- Estrutura que já existe no Supabase, reconstruída para o ensaio.
create role authenticated;
create role anon;

create schema if not exists auth;
create table auth.users (id uuid primary key);
-- auth.uid() da sessão: quem está logado no ensaio.
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('ensaio.auth_uid', true), '')::uuid;
$$;

create table public.perfis_acesso (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique
);

create table public.usuarios (
  id uuid primary key default gen_random_uuid(),
  auth_id uuid references auth.users(id),
  nome_completo text,
  cargo text,
  foto_url text,
  status text not null default 'ativo',
  perfil_id uuid references public.perfis_acesso(id)
);

create table public.perfis_permissoes (
  id uuid primary key default gen_random_uuid(),
  perfil_id uuid not null references public.perfis_acesso(id),
  modulo text not null,
  pode_visualizar boolean not null default false,
  pode_cadastrar boolean not null default false,
  pode_editar boolean not null default false,
  pode_excluir boolean not null default false,
  pode_aprovar boolean not null default false,
  pode_visualizar_valores boolean not null default false,
  unique (perfil_id, modulo),
  -- A lista fixa de módulos: é ela que a migration precisa relaxar.
  constraint perfis_permissoes_modulo_check check (modulo in (
    'dashboard','saldos','fornecedores','certidoes','pagamentos','transferencias',
    'tarefas','historico','relatorios','auditoria','configuracoes','usuarios','backup'
  ))
);

create table public.permissoes_excecao (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios(id),
  modulo text not null,
  pode_visualizar boolean,
  pode_cadastrar boolean,
  pode_editar boolean,
  pode_excluir boolean,
  pode_aprovar boolean,
  pode_visualizar_valores boolean,
  unique (usuario_id, modulo),
  constraint permissoes_excecao_modulo_check check (modulo in (
    'dashboard','saldos','fornecedores','certidoes','pagamentos','transferencias',
    'tarefas','historico','relatorios','auditoria','configuracoes','usuarios','backup'
  ))
);

create view public.permissoes_efetivas as
select
  u.id as usuario_id,
  pp.modulo,
  coalesce(ex.pode_visualizar, pp.pode_visualizar) as pode_visualizar,
  coalesce(ex.pode_cadastrar, pp.pode_cadastrar) as pode_cadastrar,
  coalesce(ex.pode_editar, pp.pode_editar) as pode_editar,
  coalesce(ex.pode_excluir, pp.pode_excluir) as pode_excluir,
  coalesce(ex.pode_aprovar, pp.pode_aprovar) as pode_aprovar,
  coalesce(ex.pode_visualizar_valores, pp.pode_visualizar_valores) as pode_visualizar_valores
from public.usuarios u
join public.perfis_permissoes pp on pp.perfil_id = u.perfil_id
left join public.permissoes_excecao ex on ex.usuario_id = u.id and ex.modulo = pp.modulo;

create table public.permissoes_especiais (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios(id),
  acao text not null,
  permitido boolean not null default false,
  unique (usuario_id, acao)
);

create or replace function public.tem_permissao_especial(p_acao text)
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((
    select pe.permitido from public.permissoes_especiais pe
     join public.usuarios u on u.id = pe.usuario_id
    where u.auth_id = auth.uid() and pe.acao = p_acao limit 1
  ), false);
$$;

create table public.secretarias (id integer primary key, nome text);

create table public.fornecedores (
  id integer generated by default as identity primary key,
  razao_social text,
  nome_fantasia text,
  cpf_cnpj text,
  secretaria_id integer references public.secretarias(id),
  ativo boolean not null default true,
  excluido_em timestamptz
);

create table public.bancos (id integer primary key, nome text);

-- A conta CARREGA SALDO: é o que o ensaio precisa vigiar.
create table public.contas_bancarias (
  id integer generated by default as identity primary key,
  nome_conta text,
  numero_conta text,
  banco_id integer references public.bancos(id),
  secretaria_id integer references public.secretarias(id),
  ativo boolean not null default true,
  saldo_atual numeric(14,2) not null default 0
);

-- A situação da nota é um ENUM no banco em uso, não texto. É por isso que ele
-- está aqui: uma coluna de texto deixaria passar comparações e gravações que o
-- enum recusa.
create type public.situacao_valor as enum (
  'em_aberto', 'programado', 'parcialmente_pago', 'pago', 'suspenso', 'cancelado'
);

create table public.valores_em_aberto (
  id integer generated by default as identity primary key,
  fornecedor_id integer not null references public.fornecedores(id),
  numero_processo text,
  numero_empenho text,
  numero_nota_fiscal text,
  data_nota_fiscal date,
  parcela text,
  valor_bruto numeric(14,2),
  valor numeric(14,2) not null default 0,
  data_vencimento date,
  situacao public.situacao_valor not null default 'em_aberto',
  created_at timestamptz not null default now()
);

create table public.auditoria_eventos (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid,
  modulo text,
  acao text,
  registro_afetado text,
  valor_anterior jsonb,
  valor_novo jsonb,
  nivel text,
  criado_em timestamptz not null default now()
);

-- Tabelas de SALDO. Ficam vazias do começo ao fim do ensaio.
create table public.saldos_historico (
  id integer generated by default as identity primary key,
  conta_id integer, data_referencia date, valor_saldo numeric(14,2)
);
create table public.pagamento_movimentacoes (
  id integer generated by default as identity primary key,
  conta_id integer, valor numeric(14,2)
);
create table public.transferencia_lotes (
  id integer generated by default as identity primary key, criado_em timestamptz default now()
);
create table public.transferencias_contas (
  id integer generated by default as identity primary key,
  lote_id integer, conta_origem_id integer, conta_destino_id integer, valor numeric(14,2)
);
